{% set name = "sorcha-addons" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dirac-institute/sorcha-addons/archive/v{{ version }}.tar.gz
  sha256: 02cd9e17c4241c2ea0aa42bc1f1b04400497a782b08c3df211311b3ab83790b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - numpy
    - sorcha >=0.6.0
    - astropy
    - scipy

test:
  imports:
    - sorcha_addons
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  license: MIT
  license_file: src/sorcha_addons/activity/lsst_comet/LICENSE
  home: https://github.com/dirac-institute/sorcha-addons
  summary: Add-on modules for the Sorcha survey simulator

extra:
  recipe-maintainers:
    - mjuric
    - mschwamb
